### PR TITLE
EOL correction

### PR DESCRIPTION
**Pull request by jmfriedt**
Software will not compile on Debian sid with gcc (Debian 11.2.0-12) 11.2.0 with the following error

src/mod_video/crrc_animation.cpp:87:34: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::ostream’ {aka ‘std::basic_ostream<char>’})
   86 |         std::cerr << "createAnimation: unknown animation type '"
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   87 |                   << type << "'" << std::cerr;
      |                   ~~~~~~~~~~~~~~ ^~ ~~~~~~~~~
      |                           |              |
      |                           |              basic_ostream<[...]>
      |                           basic_ostream<[...]>

corrected with this PR.

### CODE REVIEW

**Comment by julled** [comment]
Thansk for this contribution. I can compile and connect crrcsim to apm with this. 
Using QGC and a USB gamepad i am also able to start a plane.

But i am running into problems when actually trying to fly a plane in crrcsim. Here is how i startup things:

1. start crrcsim
2. start apm simu
3. start qgc
4. qgc: calibrate joystick in 
5. mavproxy: calibrate sensors
* accelcalsimple
* gyrocal
* ahrstrim

But when i try to let apm fly a mission in automode, the plane doesnt takeoff or crash. Did you experience similar behaviour?

Which ardupilot version did youi use in the simulator? Which airframe did you use?
